name: Crystal CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-19.04
    
    container:
      image: crystallang/crystal
    
    steps:
    - uses: actions/checkout@v1
    - name: Install tesseract
      run: |
        apt-get update
        apt-get install tesseract-ocr tesseract-ocr-eng ghostscript -y
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
